name: Run tests
env:
  ALLURE_VERSION: "2.10.0"
  
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  repository_dispatch:
    types:
      - webhook

jobs:
  build:
    name: Tests on JDK
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [11, 13, 14, 15, 17, 18]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          java-package: jdk
          cache: 'gradle'

      - name: Tests
        id: functests
        timeout-minutes: 15
        continue-on-error: true
        run: ./gradlew test -Pdriver=chrome

      - name: Collect reports
        run: |
          echo --------------- Collecting Allure Reports.... ------------------
          zip -r allure-report.zip ./allure-report/  

      - name: Upload Allure report
        uses: actions/upload-artifact@master
        with:
          name: allure-report-jdk${{ matrix.java }}
          path: ./allure-report

      - name: Check tests are passed
        if: ${{ steps.functests.outcome != 'success' }}
        run: |
          echo Tests result: ${{ steps.functests.outcome }}
          exit 1
